name: Android Detox CI

on: [release]

jobs:
  build-and-test:
    runs-on: macOS-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "10"
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Android CI
        timeout-minutes: 10
        env:
          ANDROID_HOME: "/Users/runner/Library/Android/sdk"
        run: ./gradlew androidCI
