name: Detox CI

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "10"
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: npm install
        run: |
          npm install;
          npm install -g detox-cli
      - name: start metro bundler
        run: |
          npm run start &
          sleep 30
      - name: setup android emulator
        run: |
          echo "home"
          ls ~
          echo "~/Android/Sdk"
          ls ~/Android/Sdk
          echo "/usr/lib"
          ls /usr/lib
          echo "/usr/lib/android-sdk"
          ls /usr/lib/android-sdk
          echo "environment"
          printenv
      - name: Sleep for 10 seconds
        run: |
          sleep 10
