name: Android Detox CI

on: [push]

jobs:
  build-and-test:
    runs-on: macOS-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "10"
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: malinskiy/action-android/install-sdk@release/0.0.3
      - uses: malinskiy/action-android/emulator-run-cmd@release/0.0.3
        with:
          cmd: ./gradlew unitTest
          api: 25
          tag: default
          abi: x86
