name: Detox CI

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: look for the android
        run: |
          echo "find the darned android"
          find / -iname "android" -print
          echo "environment"
          printenv
      - name: Sleep for 10 seconds
        run: |
          sleep 10
