name: Detox CI

on: [push]

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "10"
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: npm install, build, and test
        env:
          ANDROID_HOME: /Users/runner/Library/Android/sdk
        run: |
          npm install;
          npm install -g detox-cli
          $ANDROID_HOME/tools/bin/sdkmanager --update --sdk_root=$ANDROID_HOME
          $ANDROID_HOME/tools/bin/sdkmanager --licenses --sdk_root=$ANDROID_HOME < ./yes.txt
          $ANDROID_HOME/tools/bin/sdkmanager --sdk_root=$ANDROID_HOME "system-images;android-28;google_apis_playstore;x86"
          echo "Finished with the licenses"
          $ANDROID_HOME/tools/bin/avdmanager create avd --name something --package "system-images;android-28;google_apis_playstore;x86" --device "Nexus 5X"
          npm run start &
          sleep 30
          detox build --configuration android.emu.debug
          detox test --configuration android.emu.debug
          brew tap wix/brew
          brew install applesimutils
          detox build --configuration ios.sim.debug
          detox test --configuration ios.sim.debug

