name: Detox CI

on: [push]

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "10"
      - name: npm install, build, and test
        run: |
          npm install;
          npm install -g detox-cli
          ~/Library/Android/sdk/tools/bin/avdmanager create avd --name something --package "system-images;android-28;google_apis_playstore;x86" --device Nexus_5X
          ~/Library/Android/sdk/emulator/emulator @something
          detox build --configuration android.emu.debug
          detox test --configuration android.emu.debug
          brew tap wix/brew
          brew install applesimutils
          detox build --configuration ios.sim.debug
          detox test --configuration ios.sim.debug

