name: Detox CI

on: [push]

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "10"
      - name: npm install, build, and test
        env:
          JAVA_HOME: "/Library/Java/JavaVirtualMachines/zulu-13.jdk/Contents/Home"
        run: |
          npm install;
          npm test;
          ./gradlew start
          detox test --configuration ios.sim.debug
          detox test --configuration android.emu.debug
          ./gradlew stop


