name: Experiment

on: [push]

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - name: Checkout
          uses: actions/checkout@v1
      - name: 'Oh hi'
        uses: '.github/actions/hello-action'
        with:
          whomst: 'Updog'


