name: iOS Detox CI

on: [push]

jobs:
  build-and-test:
    runs-on: macOS-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "10"
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: npm install
        run: ./gradlew npmInstall
      - name: install applesimutils
        run: ./gradlew installApplesimutils
      - name: start metro bundler
        run: ./gradlew launchMetroBundler
      - name: run ios build and test
        timeout-minutes: 5
        run: ./gradlew iosTest
