name: iOS Detox CI

on: [push]

jobs:
  build-and-test:
    runs-on: macOS-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "10"
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: npm install
        run: |
          npm install;
          npm install -g detox-cli
      - name: start metro bundler
        run: |
          npm run start &
          sleep 30
      - name: run ios build and test
        timeout-minutes: 5
        run: |
          brew tap wix/brew
          brew install applesimutils
          detox build --configuration ios.sim.debug
          detox test --configuration ios.sim.debug
      - name: Sleep for 10 seconds
        run: |
          sleep 10
